server:
  port: 8085

spring:
  application:
    name: discoveryService

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

